// Create diary for each player
_null = player createDiaryRecord ["Diary", [localize "str_a3_diary_execution_title", format ["%1%4%2%4%3",localize "STR_A3_EscapeFromTanoa_execution01",format [localize "STR_A3_EscapeFromTanoa_execution02","</marker>", "<marker name = 'BIS_mrkGeorgetown'>","<marker name = 'BIS_mrkAirfield'>","<marker name = 'BIS_mrkLijnPort'>","<marker name = 'BIS_mrkLijnAirport'>"],localize "STR_A3_EscapeFromTanoa_execution03","<br /><br />"]]];

// Add respawn tickets if set to individual unit
if (missionNamespace getVariable "BIS_respawnTickets" == 0) then {[player,1] call BIS_fnc_respawnTickets};
if (missionNamespace getVariable "BIS_respawnTickets" == 1) then {[player,2] call BIS_fnc_respawnTickets};
if (missionNamespace getVariable "BIS_respawnTickets" == 2) then {[player,3] call BIS_fnc_respawnTickets};
if (missionNamespace getVariable "BIS_respawnTickets" == 3) then {[player,4] call BIS_fnc_respawnTickets};
if (missionNamespace getVariable "BIS_respawnTickets" == 4) then {[player,5] call BIS_fnc_respawnTickets};
if (missionNamespace getVariable "BIS_respawnTickets" == 5) then {[player,6] call BIS_fnc_respawnTickets};
if (missionNamespace getVariable "BIS_respawnTickets" == 10) then {[player,11] call BIS_fnc_respawnTickets};

// Handle JIP respawn
missionNamespace setVariable ["_initialRespawn", addMissionEventHandler ["PreloadFinished",
{
	removeMissionEventHandler ["PreloadFinished", missionNamespace getVariable ["_initialRespawn", -1]];
	missionNamespace setVariable ["_initialRespawn", nil];

	if (didJIP and (time > 30)) then
	{
		player enableSimulationGlobal false;
		player enableSimulation false;
		player hideObjectGlobal true;
		player hideObject true;
		forceRespawn player;
		deleteVehicle player;
	};
}]];

// Set available loadout
if (typeOf player == "B_T_Soldier_SL_F") then {
	if (BIS_loadoutLevel == 0) then {[player,"B_SquadLeader"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["arifle_SPAR_01_khk_F","","acc_pointer_IR","optic_ERCO_blk_F",["30Rnd_556x45_Stanag_Tracer_Red",30],[],""],[],["hgun_P07_khk_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_B_T_Soldier_SL_F",[["FirstAidKit",1],["SmokeShell",2,1],["16Rnd_9x21_Mag",2,16]]],["V_PlateCarrierSpec_tna_F",[["30Rnd_556x45_Stanag_Tracer_Red",7,30],["HandGrenade",2,1]]],[],"H_HelmetB_Enh_tna_F",nil,["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_tna_F"]]};
	if (BIS_loadoutLevel == 1) then {[player,"B_SquadLeader_L"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["arifle_SPAR_01_khk_F","","acc_flashlight","optic_ERCO_blk_F",["30Rnd_556x45_Stanag_Tracer_Red",30],[],""],[],["hgun_P07_khk_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_B_T_Soldier_SL_F",[["FirstAidKit",1],["SmokeShell",2,1],["16Rnd_9x21_Mag",2,16]]],["V_PlateCarrierSpec_tna_F",[["30Rnd_556x45_Stanag_Tracer_Red",3,30],["HandGrenade",2,1]]],[],"H_HelmetB_Enh_tna_F",nil,["Binocular","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""]]};
	if (BIS_loadoutLevel == 2) then {[player,"B_SquadLeader_S"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["arifle_SPAR_01_khk_F","","acc_flashlight","",["30Rnd_556x45_Stanag_Tracer_Red",30],[],""],[],["hgun_P07_khk_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_B_T_Soldier_SL_F",[["FirstAidKit",1],["SmokeShell",2,1],["16Rnd_9x21_Mag",2,16]]],["V_PlateCarrierSpec_tna_F",[["30Rnd_556x45_Stanag_Tracer_Red",1,30],["HandGrenade",2,1]]],[],"H_HelmetB_Enh_tna_F",nil,["Binocular","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]};
};

if (typeOf player == "B_T_soldier_M_F") then {
	if (BIS_loadoutLevel == 0) then {[player,"B_Marksman"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["arifle_SPAR_03_khk_F","","acc_pointer_IR","optic_ERCO_blk_F",["20Rnd_762x51_Mag",20],[],"bipod_01_F_blk"],[],["hgun_P07_khk_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_B_T_Soldier_SL_F",[["FirstAidKit",1],["SmokeShell",2,1],["16Rnd_9x21_Mag",2,16]]],["V_PlateCarrier1_tna_F",[["20Rnd_762x51_Mag",7,20],["HandGrenade",2,1]]],[],"H_HelmetB_Light_tna_F",nil,["Rangefinder","","","",[],[],""],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_tna_F"]]};
	if (BIS_loadoutLevel == 1) then {[player,"B_Marksman_L"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["arifle_SPAR_03_khk_F","","acc_flashlight","optic_ERCO_blk_F",["20Rnd_762x51_Mag",20],[],"bipod_01_F_blk"],[],["hgun_P07_khk_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_B_T_Soldier_SL_F",[["FirstAidKit",1],["SmokeShell",2,1],["16Rnd_9x21_Mag",2,16]]],["V_PlateCarrier1_tna_F",[["20Rnd_762x51_Mag",3,20],["HandGrenade",2,1]]],[],"H_HelmetB_Light_tna_F",nil,["Binocular","","","",[],[],""],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]};
	if (BIS_loadoutLevel == 2) then {[player,"B_Marksman_S"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["arifle_SPAR_03_khk_F","","acc_flashlight","",["20Rnd_762x51_Mag",20],[],"bipod_01_F_blk"],[],["hgun_P07_khk_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_B_T_Soldier_SL_F",[["FirstAidKit",1],["SmokeShell",2,1],["16Rnd_9x21_Mag",2,16]]],["V_PlateCarrier1_tna_F",[["20Rnd_762x51_Mag",1,20],["HandGrenade",2,1]]],[],"H_HelmetB_Light_tna_F",nil,[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]};
};

if (typeOf player == "B_T_soldier_AR_F") then {
	if (BIS_loadoutLevel == 0) then {[player,"B_Autorifleman"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["arifle_SPAR_02_khk_F","","acc_pointer_IR","optic_Aco",["150Rnd_556x45_Drum_Mag_F",150],[],"bipod_01_F_blk"],[],["hgun_P07_khk_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_B_T_Soldier_AR_F",[["FirstAidKit",1],["SmokeShell",2,1],["16Rnd_9x21_Mag",2,16]]],["V_PlateCarrier2_tna_F",[["150Rnd_556x45_Drum_Mag_F",3,150],["HandGrenade",2,1]]],[],"H_HelmetB_tna_F",nil,[],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_tna_F"]]};
	if (BIS_loadoutLevel == 1) then {[player,"B_Autorifleman_L"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["arifle_SPAR_02_khk_F","","acc_flashlight","optic_Aco",["150Rnd_556x45_Drum_Mag_F",150],[],"bipod_01_F_blk"],[],["hgun_P07_khk_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_B_T_Soldier_AR_F",[["FirstAidKit",1],["SmokeShell",2,1],["16Rnd_9x21_Mag",2,16]]],["V_PlateCarrier2_tna_F",[["150Rnd_556x45_Drum_Mag_F",1,150],["HandGrenade",2,1]]],[],"H_HelmetB_tna_F",nil,[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]};
	if (BIS_loadoutLevel == 2) then {[player,"B_Autorifleman_S"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["arifle_SPAR_02_khk_F","","acc_flashlight","",["150Rnd_556x45_Drum_Mag_F",150],[],"bipod_01_F_blk"],[],["hgun_P07_khk_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_B_T_Soldier_AR_F",[["FirstAidKit",1],["SmokeShell",2,1],["16Rnd_9x21_Mag",2,16]]],["V_PlateCarrier2_tna_F",[["HandGrenade",2,1]]],[],"H_HelmetB_tna_F",nil,[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]};
};

if (typeOf player == "B_T_soldier_GL_F") then {
	if (BIS_loadoutLevel == 0) then {[player,"B_Grenadier"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["arifle_SPAR_01_GL_khk_F","","acc_pointer_IR","optic_Aco",["30Rnd_556x45_Stanag_red",30],["1Rnd_HE_Grenade_shell",1],""],[],["hgun_P07_khk_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_B_T_Soldier_AR_F",[["FirstAidKit",1],["SmokeShell",2,1],["16Rnd_9x21_Mag",2,16]]],["V_PlateCarrierGL_tna_F",[["30Rnd_556x45_Stanag_red",7,30],["HandGrenade",2,1],["1Rnd_HE_Grenade_shell",5,1]]],[],"H_HelmetB_tna_F",nil,[],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_tna_F"]]};
	if (BIS_loadoutLevel == 1) then {[player,"B_Grenadier_L"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["arifle_SPAR_01_GL_khk_F","","acc_flashlight","optic_Aco",["30Rnd_556x45_Stanag_red",30],["1Rnd_HE_Grenade_shell",1],""],[],["hgun_P07_khk_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_B_T_Soldier_AR_F",[["FirstAidKit",1],["SmokeShell",2,1],["16Rnd_9x21_Mag",2,16]]],["V_PlateCarrierGL_tna_F",[["30Rnd_556x45_Stanag_red",3,30],["HandGrenade",2,1],["1Rnd_HE_Grenade_shell",3,1]]],[],"H_HelmetB_tna_F",nil,[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]};
	if (BIS_loadoutLevel == 2) then {[player,"B_Grenadier_S"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["arifle_SPAR_01_GL_khk_F","","acc_flashlight","",["30Rnd_556x45_Stanag_red",30],["1Rnd_HE_Grenade_shell",1],""],[],["hgun_P07_khk_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_B_T_Soldier_AR_F",[["FirstAidKit",1],["SmokeShell",2,1],["16Rnd_9x21_Mag",2,16]]],["V_PlateCarrierGL_tna_F",[["30Rnd_556x45_Stanag_red",1,30],["HandGrenade",2,1],["1Rnd_HE_Grenade_shell",1,1]]],[],"H_HelmetB_tna_F",nil,[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]};
};

if (typeOf player == "B_T_soldier_F") then {
	if (BIS_loadoutLevel == 0) then {[player,"B_Rifleman"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["arifle_SPAR_01_khk_F","","acc_pointer_IR","optic_Aco",["30Rnd_556x45_Stanag_red",30],[],""],[],["hgun_P07_khk_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_B_T_Soldier_AR_F",[["FirstAidKit",1],["SmokeShell",2,1],["16Rnd_9x21_Mag",2,16]]],["V_PlateCarrier2_tna_F",[["30Rnd_556x45_Stanag_red",7,30],["HandGrenade",2,1]]],[],"H_HelmetB_tna_F",nil,[],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_tna_F"]]};
	if (BIS_loadoutLevel == 1) then {[player,"B_Rifleman_L"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["arifle_SPAR_01_khk_F","","acc_flashlight","optic_Aco",["30Rnd_556x45_Stanag_red",30],[],""],[],["hgun_P07_khk_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_B_T_Soldier_AR_F",[["FirstAidKit",1],["SmokeShell",2,1],["16Rnd_9x21_Mag",2,16]]],["V_PlateCarrier2_tna_F",[["30Rnd_556x45_Stanag_red",3,30],["HandGrenade",2,1]]],[],"H_HelmetB_tna_F",nil,[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]};
	if (BIS_loadoutLevel == 2) then {[player,"B_Rifleman_S"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["arifle_SPAR_01_khk_F","","acc_flashlight","",["30Rnd_556x45_Stanag_red",30],[],""],[],["hgun_P07_khk_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_B_T_Soldier_AR_F",[["FirstAidKit",1],["SmokeShell",2,1],["16Rnd_9x21_Mag",2,16]]],["V_PlateCarrier2_tna_F",[["30Rnd_556x45_Stanag_red",1,30],["HandGrenade",2,1]]],[],"H_HelmetB_tna_F",nil,[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]};
};

if (typeOf player == "B_T_soldier_LAT_F") then {
	if (BIS_loadoutLevel == 0) then {[player,"B_AT"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["arifle_SPAR_01_khk_F","","acc_pointer_IR","optic_Aco",["30Rnd_556x45_Stanag_red",30],[],""],["launch_NLAW_F","","","",["NLAW_F",1],[],""],["hgun_P07_khk_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_B_T_Soldier_AR_F",[["FirstAidKit",1],["16Rnd_9x21_Mag",2,16],["SmokeShell",2,1]]],["V_PlateCarrier2_tna_F",[["30Rnd_556x45_Stanag_red",7,30],["HandGrenade",2,1]]],["B_AssaultPack_tna_F",[["NLAW_F",1,1]]],"H_HelmetB_tna_F",nil,[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles_tna_F"]]};
	if (BIS_loadoutLevel == 1) then {[player,"B_AT_L"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["arifle_SPAR_01_khk_F","","acc_flashlight","optic_Aco",["30Rnd_556x45_Stanag_red",30],[],""],["launch_NLAW_F","","","",["NLAW_F",1],[],""],["hgun_P07_khk_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_B_T_Soldier_AR_F",[["FirstAidKit",1],["16Rnd_9x21_Mag",2,16],["SmokeShell",2,1]]],["V_PlateCarrier2_tna_F",[["30Rnd_556x45_Stanag_red",3,30],["HandGrenade",2,1]]],["B_AssaultPack_tna_F",[["NLAW_F",1,1]]],"H_HelmetB_tna_F",nil,[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]};
	if (BIS_loadoutLevel == 2) then {[player,"B_AT_S"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["arifle_SPAR_01_khk_F","","acc_flashlight","",["30Rnd_556x45_Stanag_red",30],[],""],["launch_NLAW_F","","","",["NLAW_F",1],[],""],["hgun_P07_khk_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_B_T_Soldier_AR_F",[["FirstAidKit",1],["16Rnd_9x21_Mag",2,16],["SmokeShell",2,1]]],["V_PlateCarrier2_tna_F",[["30Rnd_556x45_Stanag_red",1,30],["HandGrenade",2,1]]],["B_AssaultPack_tna_F",[["NLAW_F",1,1]]],"H_HelmetB_tna_F",nil,[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]};
};

if (typeOf player == "B_T_engineer_F") then {
	if (BIS_loadoutLevel == 0) then {[player,"B_Engineer"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["arifle_SPAR_01_khk_F","","acc_pointer_IR","optic_Aco",["30Rnd_556x45_Stanag_red",30],[],""],[],["hgun_P07_khk_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_B_T_Soldier_AR_F",[["FirstAidKit",1],["SmokeShell",2,1],["16Rnd_9x21_Mag",2,16]]],["V_PlateCarrier1_tna_F",[["30Rnd_556x45_Stanag_red",7,30]]],["B_AssaultPack_tna_F",[["ToolKit",1],["MineDetector",1],["DemoCharge_Remote_Mag",2,1]]],"H_HelmetB_Light_tna_F",nil,[],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_tna_F"]]};
	if (BIS_loadoutLevel == 1) then {[player,"B_Engineer_L"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["arifle_SPAR_01_khk_F","","acc_flashlight","optic_Aco",["30Rnd_556x45_Stanag_red",30],[],""],[],["hgun_P07_khk_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_B_T_Soldier_AR_F",[["FirstAidKit",1],["SmokeShell",2,1],["16Rnd_9x21_Mag",2,16]]],["V_PlateCarrier1_tna_F",[["30Rnd_556x45_Stanag_red",3,30]]],["B_AssaultPack_tna_F",[["ToolKit",1],["MineDetector",1],["DemoCharge_Remote_Mag",2,1]]],"H_HelmetB_Light_tna_F",nil,[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]};
	if (BIS_loadoutLevel == 2) then {[player,"B_Engineer_S"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["arifle_SPAR_01_khk_F","","acc_flashlight","",["30Rnd_556x45_Stanag_red",30],[],""],[],["hgun_P07_khk_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_B_T_Soldier_AR_F",[["FirstAidKit",1],["SmokeShell",2,1],["16Rnd_9x21_Mag",2,16]]],["V_PlateCarrier1_tna_F",[["30Rnd_556x45_Stanag_red",1,30]]],["B_AssaultPack_tna_F",[["ToolKit",1],["MineDetector",1],["DemoCharge_Remote_Mag",2,1]]],"H_HelmetB_Light_tna_F",nil,[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]};
};

if (typeOf player == "B_T_medic_F") then {
	if (BIS_loadoutLevel == 0) then {[player,"B_CombatLifesaver"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["arifle_SPAR_01_khk_F","","acc_pointer_IR","optic_Aco",["30Rnd_556x45_Stanag_red",30],[],""],[],["hgun_P07_khk_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_B_T_Soldier_SL_F",[["FirstAidKit",1],["SmokeShellBlue",4,1],["16Rnd_9x21_Mag",2,16]]],["V_PlateCarrierSpec_tna_F",[["30Rnd_556x45_Stanag_red",7,30]]],["B_AssaultPack_tna_F",[["Medikit",1]]],"H_HelmetB_Enh_tna_F",nil,[],["ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_tna_F"]]};
	if (BIS_loadoutLevel == 1) then {[player,"B_CombatLifesaver_L"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["arifle_SPAR_01_khk_F","","acc_flashlight","optic_Aco",["30Rnd_556x45_Stanag_red",30],[],""],[],["hgun_P07_khk_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_B_T_Soldier_SL_F",[["FirstAidKit",1],["SmokeShellBlue",4,1],["16Rnd_9x21_Mag",2,16]]],["V_PlateCarrierSpec_tna_F",[["30Rnd_556x45_Stanag_red",3,30]]],["B_AssaultPack_tna_F",[["Medikit",1]]],"H_HelmetB_Enh_tna_F",nil,[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]};
	if (BIS_loadoutLevel == 2) then {[player,"B_CombatLifesaver_S"] call BIS_fnc_addRespawninventory; player setUnitLoadout [["arifle_SPAR_01_khk_F","","acc_flashlight","",["30Rnd_556x45_Stanag_red",30],[],""],[],["hgun_P07_khk_F","","","",["16Rnd_9x21_Mag",16],[],""],["U_B_T_Soldier_SL_F",[["FirstAidKit",1],["SmokeShellBlue",4,1],["16Rnd_9x21_Mag",2,16]]],["V_PlateCarrierSpec_tna_F",[["30Rnd_556x45_Stanag_red",1,30]]],["B_AssaultPack_tna_F",[["Medikit",1]]],"H_HelmetB_Enh_tna_F",nil,[],["ItemMap","","ItemRadio","ItemCompass","ItemWatch",""]]};
};
