name = "ZluskeN Loadouts"
prefix = "zsn_loadouts"
version = "0.0.0"
author = "ZluskeN"
files = [
    "five-seven.paa",
    "mod.cpp",
]
key_name = "zsn"
reuse_private_key = true
authority = "zsn"
sig_version = 3
