/*
	Project: 	R&D
	Author: 	Sho
	Date: 		18-04-2016

	Campaign Lobby: Mission Header
*/

class CampaignLobby
{
	class Missions
	{
		class EXP_m01
		{
			name			= "$STR_A3_exp_m01_missionTitle";
			restrictedName	= $STR_A3_RscDisplayCampaignLobby_MissionOption_Restricted;

			briefingImage	= "\a3\Missions_F_Exp\data\Img\EXP_m01_Overview_large_CO.paa";
			overlayImage	= "\a3\Missions_F_Exp\data\Img\EXP_m01_Overview02_large_CO.paa";
			debriefingImage	= "\a3\Missions_F_Exp\data\Img\EXP_m01_Overview03_large_CO.paa";
			restrictedImage	= "\A3\Missions_F_Exp\data\Img\lobby\ui_campaign_lobby_restricted_ca.paa";

			briefingText	= "$STR_A3_exp_m01_missionoverview";
			debriefingText	= "$STR_A3_exp_m01_debriefing";
			restrictedText	= "$STR_A3_RscDisplayCampaignLobby_MissionOption_RestrictedText";
		};

		class EXP_m02
		{
			name			= "$STR_A3_EXP_m02_missionTitle";
			restrictedName	= $STR_A3_RscDisplayCampaignLobby_MissionOption_Restricted;

			briefingImage	= "\a3\Missions_F_Exp\data\Img\EXP_m02_Overview_large_CO.paa";
			overlayImage	= "\a3\Missions_F_Exp\data\Img\EXP_m02_Overview02_large_CO.paa";
			debriefingImage	= "\a3\Missions_F_Exp\data\Img\EXP_m02_Overview03_large_CO.paa";
			restrictedImage	= "\A3\Missions_F_Exp\data\Img\lobby\ui_campaign_lobby_restricted_ca.paa";

			briefingText	= "$STR_A3_EXP_m02_overview";
			debriefingText	= "$STR_A3_EXP_m02_Debriefing_Description";
			restrictedText	= "$STR_A3_RscDisplayCampaignLobby_MissionOption_RestrictedText";
		};

		class EXP_m03
		{
			name			= "$STR_A3_EXP_m03_missionTitle";
			restrictedName	= $STR_A3_RscDisplayCampaignLobby_MissionOption_Restricted;

			briefingImage	= "\a3\Missions_F_Exp\data\Img\EXP_m03_Overview_large_CO.paa";
			overlayImage	= "\a3\Missions_F_Exp\data\Img\EXP_m03_Overview02_large_CO.paa";
			debriefingImage = "\a3\Missions_F_Exp\data\Img\EXP_m03_Overview03_large_CO.paa";
			restrictedImage = "\A3\Missions_F_Exp\data\Img\lobby\ui_campaign_lobby_restricted_ca.paa";

			briefingText	= "$STR_A3_EXP_m03_overview";
			debriefingText	= "$STR_A3_EXP_m03_Debriefing_1_Description";
			restrictedText	= "$STR_A3_RscDisplayCampaignLobby_MissionOption_RestrictedText";
		};

		class EXP_m04
		{
			name			= "$STR_A3_EXP_m04_MissionTitle";
			restrictedName	= $STR_A3_RscDisplayCampaignLobby_MissionOption_Restricted;

			briefingImage	= "\a3\Missions_F_Exp\data\Img\EXP_m04_Overview_large_CO.paa";
			overlayImage	= "\a3\Missions_F_Exp\data\Img\EXP_m04_Overview02_large_CO.paa";
			debriefingImage	= "\a3\Missions_F_Exp\data\Img\EXP_m04_Overview03_large_CO.paa";
			restrictedImage	= "\A3\Missions_F_Exp\data\Img\lobby\ui_campaign_lobby_restricted_ca.paa";

			briefingText	= "$STR_A3_EXP_m04_Overview";
			debriefingText	= "$STR_A3_EXP_m04_END1_Description";
			restrictedText	= "$STR_A3_RscDisplayCampaignLobby_MissionOption_RestrictedText";
		};

		class EXP_m05
		{
			name			= "$STR_A3_Exp_m05_MissionTitle";
			restrictedName	= $STR_A3_RscDisplayCampaignLobby_MissionOption_Restricted;

			briefingImage	= "\a3\Missions_F_Exp\data\Img\EXP_m05_Overview_large_CO.paa";
			overlayImage	= "\a3\Missions_F_Exp\data\Img\EXP_m05_Overview02_large_CO.paa";
			debriefingImage	= "\a3\Missions_F_Exp\data\Img\EXP_m05_Overview03_large_CO.paa";
			restrictedImage	= "\A3\Missions_F_Exp\data\Img\lobby\ui_campaign_lobby_restricted_ca.paa";

			briefingText	= "$STR_A3_exp_m05_overview";
			debriefingText	= "$STR_A3_Exp_m05_Debriefing";
			restrictedText	= "$STR_A3_RscDisplayCampaignLobby_MissionOption_RestrictedText";
		};

		class EXP_m06
		{
			name			= "$STR_A3_EXP_m06_MissionTitle";
			restrictedName	= $STR_A3_RscDisplayCampaignLobby_MissionOption_Restricted;

			briefingImage	= "\a3\Missions_F_Exp\data\Img\EXP_m06_Overview_large_CO.paa";
			overlayImage	= "\a3\Missions_F_Exp\data\Img\EXP_m06_Overview02_large_CO.paa";
			debriefingImage	= "\a3\Missions_F_Exp\data\Img\EXP_m06_Overview03_large_CO.paa";
			restrictedImage	= "\A3\Missions_F_Exp\data\Img\lobby\ui_campaign_lobby_restricted_ca.paa";

			briefingText	= "$STR_A3_EXP_m06_Overview";
			debriefingText	= "$STR_A3_EXP_m06_END1_Description";
			restrictedText	= "$STR_A3_RscDisplayCampaignLobby_MissionOption_RestrictedText";
		};

		class EXP_m07
		{
			name			= "$STR_A3_exp_m07_missionTitle";
			restrictedName	= $STR_A3_RscDisplayCampaignLobby_MissionOption_Restricted;

			briefingImage	= "\a3\Missions_F_Exp\data\Img\EXP_m07_Overview_large_CO.paa";
			overlayImage	= "\a3\Missions_F_Exp\data\Img\EXP_m07_Overview02_large_CO.paa";
			debriefingImage	= "\a3\Missions_F_Exp\data\Img\EXP_m07_Overview03_large_CO.paa";
			restrictedImage	= "\A3\Missions_F_Exp\data\Img\lobby\ui_campaign_lobby_restricted_ca.paa";

			briefingText	= "$STR_A3_exp_m07_missionoverview";
			debriefingText	= "$STR_A3_exp_m07_end01";
			restrictedText	= "$STR_A3_RscDisplayCampaignLobby_MissionOption_RestrictedText";
		};
	};
};
