/*
	Project: 	R&D
	Author: 	Endstar
	Date: 		18-04-2016

	Campaign Lobby: UI Defines
*/

//////////////////////////////
//		FONTS

#define xGUI_FONT_NORMAL								"PuristaMedium"
#define xGUI_FONT_BOLD									"PuristaSemibold"
#define xGUI_FONT_THIN									"PuristaLight"
#define xGUI_FONT_MONO									"EtelkaMonospacePro"
#define xGUI_FONT_NARROW								"EtelkaNarrowMediumPro"

//////////////////////////////
//		COLOURS

#define CAMPAIGN_LOBBY_COLOR_WHITE						"FFFFFF"
#define CAMPAIGN_LOBBY_COLOR_BLACK						"000000"
#define CAMPAIGN_LOBBY_COLOR_RED						"E62C33"
#define CAMPAIGN_LOBBY_COLOR_GREEN						"00FF90"
#define CAMPAIGN_LOBBY_COLOR_YELLOW						"FFEA00"
#define CAMPAIGN_LOBBY_COLOR_ORANGE						"FFC000"
#define CAMPAIGN_LOBBY_COLOR_BLUE						"00C6FF"
#define CAMPAIGN_LOBBY_COLOR_GREY						"202020"

#define CAMPAIGN_LOBBY_COLOR_BUTTON						"44443A"

#define ALPHA_100										"FF"
#define ALPHA_80										"C6"
#define ALPHA_75										"B9"
#define ALPHA_50										"77"
#define ALPHA_25										"3B"
#define ALPHA_25										"3B"
#define ALPHA_10										"1C"
#define ALPHA_00										"00"

//////////////////////////////
//		PICTURE + TEXT + FONTSIZE

#define TEXT_CAMPAIGN_LOBBY_CTRG_HEADER01				"CTRG"
#define TEXT_CAMPAIGN_LOBBY_CTRG_HEADER02				"CTRGCENTRAL"

#define FONTSIZE_CAMPAIGN_LOBBY_CTRG_HEADER01			(TREE_LOGO_H * 0.875)
#define FONTSIZE_CAMPAIGN_LOBBY_CTRG_HEADER02			(FONTSIZE_CAMPAIGN_LOBBY_CTRG_HEADER01)

#define FONTSIZE_CAMPAIGN_LOBBY_INTEL_TITLE				(MISSION_INTEL_TITLE_H)
#define FONTSIZE_CAMPAIGN_LOBBY_INTEL_STATUS			(MISSION_INTEL_TITLE_H * 0.75)
#define FONTSIZE_CAMPAIGN_LOBBY_INTEL_COMPLETE			(MISSION_OVERLAY_COMPLETE_H * 0.75)

#define FONTSIZE_CAMPAIGN_LOBBY_INTEL_DESCRIPTION		(xGUI_GRID_H * 0.75)

#define FONTSIZE_CAMPAIGN_LOBBY_SETTINGS_TITLE			(xGUI_GRID_H * 0.875)
#define FONTSIZE_CAMPAIGN_LOBBY_SETTINGS_MODE			(xGUI_GRID_H * 0.875)

#define PICTURE_CAMPAIGN_LOBBY_BACKGROUND				"A3\Missions_F_Exp\data\Img\lobby\ui_campaign_lobby_background_co.paa"
#define PICTURE_CAMPAIGN_LOBBY_BACKGROUND2				"A3\Missions_F_Exp\data\Img\lobby\ui_campaign_lobby_background2_co.paa"

#define PICTURE_CAMPAIGN_LOBBY_TABLET_TOP				"A3\Missions_F_Exp\data\Img\lobby\ui_campaign_lobby_background_tablet_top_co.paa"
#define PICTURE_CAMPAIGN_LOBBY_TABLET_BOTTOM			"A3\Missions_F_Exp\data\Img\lobby\ui_campaign_lobby_background_tablet_bottom_co.paa"
#define PICTURE_CAMPAIGN_LOBBY_TABLET_LEFT				"A3\Missions_F_Exp\data\Img\lobby\ui_campaign_lobby_background_tablet_left_co.paa"
#define PICTURE_CAMPAIGN_LOBBY_TABLET_RIGHT				"A3\Missions_F_Exp\data\Img\lobby\ui_campaign_lobby_background_tablet_right_co.paa"
#define PICTURE_CAMPAIGN_LOBBY_TABLET_TOPLEFT			"A3\Missions_F_Exp\data\Img\lobby\ui_campaign_lobby_background_tablet_topleftcorner_co.paa"
#define PICTURE_CAMPAIGN_LOBBY_TABLET_TOPRIGHT			"A3\Missions_F_Exp\data\Img\lobby\ui_campaign_lobby_background_tablet_toprightcorner_co.paa"
#define PICTURE_CAMPAIGN_LOBBY_TABLET_BOTTOMLEFT		"A3\Missions_F_Exp\data\Img\lobby\ui_campaign_lobby_background_tablet_bottomleftcorner_co.paa"
#define PICTURE_CAMPAIGN_LOBBY_TABLET_BOTTOMRIGHT		"A3\Missions_F_Exp\data\Img\lobby\ui_campaign_lobby_background_tablet_bottomrightcorner_co.paa"
#define PICTURE_CAMPAIGN_LOBBY_TABLET_BUTTONBAR			"A3\Missions_F_Exp\data\Img\lobby\ui_campaign_lobby_background_tablet_buttonbar_co.paa"
#define PICTURE_CAMPAIGN_LOBBY_TABLET_BUTTON_SEARCH		"A3\Missions_F_Exp\data\Img\lobby\ui_campaign_lobby_background_tablet_button_search_ca.paa"
#define PICTURE_CAMPAIGN_LOBBY_TABLET_BUTTON_RESPAWN	"A3\Missions_F_Exp\data\Img\lobby\ui_campaign_lobby_background_tablet_button_respawn02_ca.paa"
#define PICTURE_CAMPAIGN_LOBBY_TABLET_BUTTON_REVIVE		"A3\Missions_F_Exp\data\Img\lobby\ui_campaign_lobby_background_tablet_button_revive02_ca.paa"
#define PICTURE_CAMPAIGN_LOBBY_TABLET_BUTTON_SETTINGS	"A3\Missions_F_Exp\data\Img\lobby\ui_campaign_lobby_background_tablet_button_settings_ca.paa"
#define PICTURE_CAMPAIGN_LOBBY_TABLET_RADIAL_BG_LEFT	"A3\Missions_F_Exp\data\Img\lobby\ui_campaign_lobby_background_tablet_radial_left_bg_ca.paa"
#define PICTURE_CAMPAIGN_LOBBY_TABLET_RADIAL_LEFT		"A3\Missions_F_Exp\data\Img\lobby\ui_campaign_lobby_background_tablet_radial_left_ca.paa"

#define PICTURE_CAMPAIGN_LOBBY_CTRG_LOGO				"A3\Missions_F_Exp\data\Img\lobby\ui_campaign_lobby_ctrg_tree_logo_ca.paa"

#define PICTURE_CAMPAIGN_LOBBY_MISSION_DEFAULT			"A3\Missions_F_Exp\data\Img\lobby\ui_campaign_lobby_mission_overview_image_placeholder_ca.paa"
#define PICTURE_CAMPAIGN_LOBBY_MISSION_FADE				"A3\Missions_F_Exp\data\Img\lobby\ui_campaign_lobby_mission_intel_gradient_ca.paa"

#define PICTURE_CAMPAIGN_LOBBY_LOGIN_KEY				"A3\Missions_F_Exp\data\Img\lobby\ui_campaign_lobby_login_key_ca.paa"
#define PICTURE_CAMPAIGN_LOBBY_LOGIN_KEY_CIRCLE01		"A3\Missions_F_Exp\data\Img\lobby\ui_campaign_lobby_login_circle01_ca.paa"
#define PICTURE_CAMPAIGN_LOBBY_LOGIN_KEY_CIRCLE02		"A3\Missions_F_Exp\data\Img\lobby\ui_campaign_lobby_login_circle02_ca.paa"

#define PICTURE_CAMPAIGN_LOBBY_PLAYER_HOST				"A3\Missions_F_Exp\data\Img\lobby\ui_campaign_lobby_icon_player_host_ca.paa"
#define PICTURE_CAMPAIGN_LOBBY_PLAYER_STATUS_READY		"A3\Missions_F_Exp\data\Img\lobby\ui_campaign_lobby_icon_player_ready_ca.paa"
#define PICTURE_CAMPAIGN_LOBBY_PLAYER_STATUS_CONNECTING	"A3\Missions_F_Exp\data\Img\lobby\ui_campaign_lobby_icon_player_connecting_ca.paa"
#define PICTURE_CAMPAIGN_LOBBY_PLAYER_STATUS_CONNECTED	"A3\Missions_F_Exp\data\Img\lobby\ui_campaign_lobby_icon_player_connected_ca.paa"

//////////////////////////////
//		PIXEL GRID DEFINES

// Gutter Defines
#define xGUI_GUTTER_W									(pixelW * 2)
#define xGUI_GUTTER_H									(pixelH * 2)

// Grid Defines
#define xGRID_SIZE										(pixelGridNoUIScale)
#define xGUI_GRID_W										(pixelW * xGRID_SIZE * 2)
#define xGUI_GRID_H										(pixelH * xGRID_SIZE * 2)

//////////////////////////////
//		DISPLAY AND CONTROLS

// Campaign Lobby Display
#define IDD_CAMPAIGN_LOBBY								50000

// Campaign Lobby IDCs
#define IDC_CAMPAIGN_LOBBY_BACKGROUND_FULL_GROUP		51000
#define IDC_CAMPAIGN_LOBBY_BACKGROUND_GROUP				51100
#define IDC_CAMPAIGN_LOBBY_BACKGROUND_LOADING_GROUP		51200
#define IDC_CAMPAIGN_LOBBY_BACKGROUND_BORDER_GROUP		51300

#define IDC_CAMPAIGN_LOBBY_TABLET_GROUP					52000
#define IDC_CAMPAIGN_LOBBY_TABLET_BUTTON_GROUP			52100
#define IDC_CAMPAIGN_LOBBY_TABLET_BUTTON_SEARCH_GROUP	52200
#define IDC_CAMPAIGN_LOBBY_TABLET_BUTTON_SETTINGS_GROUP	52300
#define IDC_CAMPAIGN_LOBBY_TABLET_BUTTON_RESPAWN_GROUP	52400
#define IDC_CAMPAIGN_LOBBY_TABLET_BUTTON_REVIVE_GROUP	52500

#define IDC_CAMPAIGN_LOBBY_TABLET_MILITARY_GROUP		52600

#define IDC_CAMPAIGN_LOBBY_MAIN_GROUP					53000
#define IDC_CAMPAIGN_LOBBY_CTRG_TREE_GROUP				53100
#define IDC_CAMPAIGN_LOBBY_CTRG_TREE_HEADER_GROUP		53200
#define IDC_CAMPAIGN_LOBBY_CTRG_TREE_STRUCTURE_GROUP	53300

#define IDC_CAMPAIGN_LOBBY_CTRG_TREE_OPTION_CORE_GROUP	53400
#define IDC_CAMPAIGN_LOBBY_CTRG_TREE_OPTION_GROUP		53500

#define IDC_CAMPAIGN_LOBBY_LOGIN_GROUP					54100
#define IDC_CAMPAIGN_LOBBY_ACCESS_KEY_GROUP				54200
#define IDC_CAMPAIGN_LOBBY_MISSION_GROUP				54300
#define IDC_CAMPAIGN_LOBBY_MISSION_VIDEO_GROUP			54400
#define IDC_CAMPAIGN_LOBBY_MISSION_INTEL_GROUP			54500
#define IDC_CAMPAIGN_LOBBY_MISSION_OVERLAY_GROUP		54600

#define IDC_CAMPAIGN_LOBBY_MISSION_PLAYER_CORE_GROUP	55000
#define IDC_CAMPAIGN_LOBBY_MISSION_PLAYER_GROUP			55100

#define IDC_CAMPAIGN_LOBBY_PROGRESS_GROUP				56000

#define IDC_CAMPAIGN_LOBBY_OVERLAY_GROUP				57000

//////////////////////////////
//		CONTROL SIZES

// Background Border
#define BORDER_GUTTER_W 								(xGUI_GRID_W * 2)
#define BORDER_GUTTER_H 								(xGUI_GRID_H * 2)

#define BORDER_LENGTH_W									(xGUI_GRID_W * 4)
#define BORDER_LENGTH_H									(xGUI_GRID_H * 4)

#define BORDER_THICKNESS_W 								(MAIN_GUTTER_W)
#define BORDER_THICKNESS_H 								(MAIN_GUTTER_H)

// Main
#define ANCHOR_CORE_GUTTER_W							(xGUI_GRID_W * 1)
#define ANCHOR_CORE_GUTTER_H							(xGUI_GRID_H * 1)

#define ANCHOR_CORE_TOP_LEFT_X							(TABLET_CORE_W + ANCHOR_CORE_GUTTER_W)
#define ANCHOR_CORE_TOP_LEFT_Y							(TABLET_CORE_H + ANCHOR_CORE_GUTTER_H)

#define ANCHOR_CORE_BOTTOM_RIGHT_X						(safeZoneW - TABLET_CORE_W - TABLET_BUTTONBAR_W - ANCHOR_CORE_GUTTER_W)
#define ANCHOR_CORE_BOTTOM_RIGHT_Y						(safeZoneH - TABLET_CORE_H - ANCHOR_CORE_GUTTER_H)

#define ANCHOR_CORE_W									(ANCHOR_CORE_BOTTOM_RIGHT_X - ANCHOR_CORE_TOP_LEFT_X)
#define ANCHOR_CORE_H									(ANCHOR_CORE_BOTTOM_RIGHT_Y - ANCHOR_CORE_TOP_LEFT_Y)

#define MAIN_GUTTER_W									(xGUI_GRID_W * 0.25)
#define MAIN_GUTTER_H									(xGUI_GRID_H * 0.25)

// Overlay
#define OVERLAY_W										(safeZoneW)
#define OVERLAY_H										(safeZoneH)

#define OVERLAY_MAIN_W									(OVERLAY_W)
#define OVERLAY_MAIN_H									(OVERLAY_H)

#define LOADING_X										(ACCESS_KEY_X + ACCESS_KEY_ICON_W + MAIN_GUTTER_W)
#define LOADING_Y										(ACCESS_KEY_Y)
#define LOADING_W										(LOADING_BAR_W)
#define LOADING_H										(LOADING_TEXT_H + LOADING_BAR_H + LOADING_GUTTER_H)

#define LOADING_TEXT_X									(0)
#define LOADING_TEXT_Y									(0)
#define LOADING_TEXT_W									(LOADING_BAR_W)
#define LOADING_TEXT_H									(xGUI_GRID_H * 2)

#define LOADING_BAR_X									(0)
#define LOADING_BAR_Y									(LOADING_TEXT_H)
#define LOADING_BAR_W									(xGUI_GRID_W * 10)
#define LOADING_BAR_H									(pixelH)

#define LOADING_GUTTER_H								(MAIN_GUTTER_H)

// Tablet
#define TABLET_X										(0)
#define TABLET_Y										(0)
#define TABLET_W										(safeZoneW)
#define TABLET_H										(safeZoneH)

// Tablet Core Width
#define TABLET_CORE_W									(xGUI_GRID_W * 1)
#define TABLET_CORE_H									(xGUI_GRID_H * 1)

// Tablet Button Bar
#define TABLET_BUTTONBAR_X								(TABLET_W - TABLET_CORE_W - TABLET_BUTTONBAR_W)
#define TABLET_BUTTONBAR_Y								(TABLET_CORE_H)
#define TABLET_BUTTONBAR_W								(xGUI_GRID_W * 4.5)
#define TABLET_BUTTONBAR_H								(TABLET_H - TABLET_CORE_H * 2)

// Tablet Outline
#define TABLET_OUTLINE_W								(pixelW * 2)
#define TABLET_OUTLINE_H								(pixelH * 2)

// Tablet Button Group
#define TABLET_BUTTON_GROUP_X							(TABLET_BUTTONBAR_X)
#define TABLET_BUTTON_GROUP_Y							(ANCHOR_CORE_GUTTER_H + xGUI_GRID_H * 0.5)
#define TABLET_BUTTON_GROUP_W							(TABLET_BUTTONBAR_W + TABLET_CORE_W - pixelW)
#define TABLET_BUTTON_GROUP_H							(TABLET_BUTTONBAR_H)

// Tablet Buttons
#define TABLET_BUTTON_X									(TABLET_BUTTONBAR_W * 0.5 - TABLET_BUTTON_W * 0.5 + TABLET_CORE_W * 0.25)
#define TABLET_BUTTON_Y									(0)
#define TABLET_BUTTON_W									(xGUI_GRID_W * 3)
#define TABLET_BUTTON_H									(xGUI_GRID_H * 3)

// Tablet Title
#define TABLET_BUTTON_TITLE_X							(TABLET_CORE_W * 0.25)
#define TABLET_BUTTON_TITLE_Y							(TABLET_BUTTON_H)
#define TABLET_BUTTON_TITLE_W							(TABLET_BUTTONBAR_W)
#define TABLET_BUTTON_TITLE_H							(xGUI_GRID_H * 1)

// Tablet Button Group Core
#define TABLET_BUTTON_CORE_X							(0)
#define TABLET_BUTTON_CORE_Y							(0)
#define TABLET_BUTTON_CORE_W							(TABLET_BUTTON_GROUP_W)
#define TABLET_BUTTON_CORE_H							(TABLET_BUTTON_H + TABLET_BUTTON_TITLE_H * 2)

// Tablet Button Gutter
#define TABLET_BUTTON_GUTTER_W							(TABLET_BUTTONBAR_W * 0.5 - TABLET_BUTTON_W * 0.5 + TABLET_CORE_W * 0.25)
#define TABLET_BUTTON_GUTTER_H							(xGUI_GRID_H * 0.25)

// Tablet Line
#define TABLET_BUTTON_LINE_SEPARATOR_X					(TABLET_CORE_W * 0.5)
#define TABLET_BUTTON_LINE_SEPARATOR_Y					(ANCHOR_CORE_GUTTER_H + TREE_HEADER_H + TREE_OPTION_ITEM_Y - xGUI_GRID_H * 0.5)
#define TABLET_BUTTON_LINE_SEPARATOR_W					(TABLET_BUTTON_GROUP_W - TABLET_CORE_W * 1.25)
#define TABLET_BUTTON_LINE_SEPARATOR_H					(pixelH)

// Tablet Military Efficiency
#define TABLET_MILITARY_GROUP_X							(TABLET_BUTTONBAR_X)
#define TABLET_MILITARY_GROUP_Y							(LOGIN_Y + PROGRESS_BUTTON_H * 0.5 - TABLET_MILITARY_RADIAL_H * 0.5 - TABLET_MILITARY_TITLE_H * 2)
#define TABLET_MILITARY_GROUP_W							(TABLET_BUTTON_GROUP_W)
#define TABLET_MILITARY_GROUP_H							(TABLET_MILITARY_RADIAL_H + TABLET_MILITARY_TITLE_H * 2)

#define TABLET_MILITARY_RADIAL_X						(TABLET_BUTTONBAR_W * 0.5 - TABLET_MILITARY_RADIAL_W * 0.5 + TABLET_CORE_W * 0.25)
#define TABLET_MILITARY_RADIAL_Y						(TABLET_MILITARY_TITLE_H * 2)
#define TABLET_MILITARY_RADIAL_W						(xGUI_GRID_W * 3)
#define TABLET_MILITARY_RADIAL_H						(xGUI_GRID_H * 3)

#define TABLET_MILITARY_TITLE_X							(TABLET_CORE_W * 0.25)
#define TABLET_MILITARY_TITLE_Y							(0)
#define TABLET_MILITARY_TITLE_W							(TABLET_BUTTON_TITLE_W)
#define TABLET_MILITARY_TITLE_H							(xGUI_GRID_H * 1)

#define TABLET_MILITARY_EFFICIENCY_X					(TABLET_MILITARY_RADIAL_X + TABLET_MILITARY_RADIAL_W * 0.5 - TABLET_MILITARY_EFFICIENCY_W * 0.5)
#define TABLET_MILITARY_EFFICIENCY_Y					(TABLET_MILITARY_RADIAL_Y + TABLET_MILITARY_RADIAL_H * 0.5 - TABLET_MILITARY_EFFICIENCY_H * 0.5)
#define TABLET_MILITARY_EFFICIENCY_W					(xGUI_GRID_W * 2)
#define TABLET_MILITARY_EFFICIENCY_H					(xGUI_GRID_H * 1)

// Tree
#define TREE_GUTTER_W									(xGUI_GRID_W * 1)
#define TREE_GUTTER_H									(xGUI_GRID_H * 1)

#define TREE_LOGO_W										(xGUI_GRID_W * 2.5)
#define TREE_LOGO_H										(xGUI_GRID_H * 2.5)

#define TREE_LOGO_X										(0)
#define TREE_LOGO_Y										(0)

#define TREE_HEADER_GUTTER_W							(MAIN_GUTTER_W * 1.5)

#define TREE_HEADER_01_W								(xGUI_GRID_W * 5)
#define TREE_HEADER_01_H								(TREE_LOGO_H)

#define TREE_HEADER_01_X								(TREE_LOGO_W + TREE_HEADER_GUTTER_W)
#define TREE_HEADER_01_Y								(TREE_LOGO_H * 0.5 - TREE_HEADER_01_H * 0.5 - xGUI_GRID_H * 0.125)

#define TREE_HEADER_02_W								(xGUI_GRID_W * 15)
#define TREE_HEADER_02_H								(TREE_HEADER_01_H)

#define TREE_HEADER_02_X								(TREE_HEADER_01_X)
#define TREE_HEADER_02_Y								(TREE_HEADER_01_H)

#define TREE_STRUCTURE_W								(TREE_LOGO_W)
#define TREE_STRUCTURE_H								(ANCHOR_CORE_H - TREE_HEADER_H - LOGIN_H - ACCESS_KEY_H - pixelH) // No idea why this pixelH is needed :/

#define TREE_STRUCTURE_X								(ANCHOR_CORE_TOP_LEFT_X)
#define TREE_STRUCTURE_Y								(ANCHOR_CORE_TOP_LEFT_Y + TREE_HEADER_H)

#define TREE_HEADER_W									(TREE_GUTTER_W + TREE_LOGO_W + TREE_HEADER_GUTTER_W + TREE_HEADER_01_W + TREE_HEADER_02_W)
#define TREE_HEADER_H									(TREE_HEADER_01_H)

#define TREE_HEADER_X									(ANCHOR_CORE_TOP_LEFT_X)
#define TREE_HEADER_Y									(ANCHOR_CORE_TOP_LEFT_Y)

#define TREE_MAIN_LINE_X								(TREE_LOGO_W * 0.5)
#define TREE_MAIN_LINE_Y								(0)

#define TREE_MAIN_LINE_W								(pixelW)
#define TREE_MAIN_LINE_H								(TREE_STRUCTURE_H)

#define TREE_OPTION_SCALE								(1.5)

#define TREE_OPTION_ICON_SIZE							(1)
#define TREE_OPTION_ICON_GUTTER_W						(MAIN_GUTTER_W)

#define TREE_OPTION_LINE_X								(TREE_MAIN_LINE_X)
#define TREE_OPTION_LINE_Y								(TREE_OPTION_ITEM_H * 0.5)

#define TREE_OPTION_LINE_W								(xGUI_GRID_W * 1)
#define TREE_OPTION_LINE_H								(pixelH)

#define TREE_OPTION_ITEM_W								(xGUI_GRID_W * 9)
#define TREE_OPTION_ITEM_H								(xGUI_GRID_H * TREE_OPTION_SCALE)

#define TREE_OPTION_ITEM_X								(TREE_MAIN_LINE_X + TREE_OPTION_LINE_W)
#define TREE_OPTION_ITEM_Y								(xGUI_GRID_H * 1)

#define TREE_OPTION_ICON_W								(xGUI_GRID_W * TREE_OPTION_ICON_SIZE)
#define TREE_OPTION_ICON_H								(xGUI_GRID_H * TREE_OPTION_ICON_SIZE)

#define TREE_OPTION_ICON_X								(TREE_OPTION_ITEM_X + TREE_OPTION_ITEM_W - TREE_OPTION_ICON_W - TREE_OPTION_ICON_GUTTER_W)
#define TREE_OPTION_ICON_Y								(TREE_OPTION_ITEM_H * 0.5 - TREE_OPTION_ICON_H * 0.5)

#define TREE_OPTION_GUTTER_H							(TREE_OPTION_ITEM_H + MAIN_GUTTER_H)
#define TREE_OPTION_GUTTER2_H							(xGUI_GRID_H * 1)

#define TREE_OPTION_X									(TREE_STRUCTURE_X)
#define TREE_OPTION_Y									(TREE_STRUCTURE_Y + TREE_OPTION_GUTTER2_H)

#define TREE_OPTION_W									(TREE_OPTION_ITEM_X + TREE_OPTION_LINE_W + TREE_OPTION_ITEM_W)
#define TREE_OPTION_H									(TREE_STRUCTURE_H - TREE_OPTION_GUTTER2_H)

// Progress Buttons
#define PROGRESS_BUTTON_W								(xGUI_GRID_W * 12 - MAIN_GUTTER_W)
#define PROGRESS_BUTTON_H								(xGUI_GRID_H * 2.5)

#define PROGRESS_BUTTON_X								(0)
#define PROGRESS_BUTTON_Y								(0)

#define PROGRESS_W										(MISSION_GROUP_W)
#define PROGRESS_H										(PROGRESS_BUTTON_H)

#define PROGRESS_X										(MISSION_GROUP_X)
#define PROGRESS_Y										(LOGIN_Y)

#define PROGRESS_APPROVE_X								(PROGRESS_W - PROGRESS_BUTTON_W)

// Login
#define LOGIN_USER_W									(xGUI_GRID_W * 5)
#define LOGIN_USER_H									(xGUI_GRID_H * 1.25)

#define LOGIN_USER_EDIT_W								(TREE_LOGO_W * 0.5 + TREE_OPTION_LINE_W + TREE_OPTION_ITEM_W - LOGIN_USER_W)
#define LOGIN_USER_EDIT_H								(LOGIN_USER_H)

#define LOGIN_PASSWORD_H								(LOGIN_USER_H - pixelH)
#define LOGIN_W											(LOGIN_USER_W + LOGIN_USER_EDIT_W)
#define LOGIN_H											(LOGIN_USER_H + LOGIN_USER_EDIT_H)

#define LOGIN_X											(ANCHOR_CORE_TOP_LEFT_X)
#define LOGIN_Y											(ANCHOR_CORE_BOTTOM_RIGHT_Y - LOGIN_H)

// Access Key
#define ACCESS_KEY_ICON_W								(TREE_LOGO_W)
#define ACCESS_KEY_ICON_H								(TREE_LOGO_H)

#define ACCESS_KEY_LINE_W								(pixelW)
#define ACCESS_KEY_LINE_H								(xGUI_GRID_H)

#define ACCESS_KEY_LINE_X								(ACCESS_KEY_ICON_W * 0.5)
#define ACCESS_KEY_LINE_Y								(ACCESS_KEY_ICON_H)

#define ACCESS_KEY_TEXT_W								(xGUI_GRID_W * 8)
#define ACCESS_KEY_TEXT_H								(xGUI_GRID_H * 1.5)

#define ACCESS_KEY_TEXT_X								(ACCESS_KEY_ICON_W + MAIN_GUTTER_W)
#define ACCESS_KEY_TEXT_Y								(ACCESS_KEY_ICON_H * 0.5 - xGUI_GRID_H * 0.125 - ACCESS_KEY_TEXT_H * 0.5)

#define ACCESS_KEY_W									(ACCESS_KEY_ICON_W + MAIN_GUTTER_W + ACCESS_KEY_TEXT_W)
#define ACCESS_KEY_H									(ACCESS_KEY_ICON_H + ACCESS_KEY_LINE_H)

#define ACCESS_KEY_X									(ANCHOR_CORE_TOP_LEFT_X)
#define ACCESS_KEY_Y									(ANCHOR_CORE_BOTTOM_RIGHT_Y - LOGIN_H - ACCESS_KEY_H)

// Core Mission Group
#define MISSION_GROUP_X									(ANCHOR_CORE_TOP_LEFT_X + TREE_OPTION_ITEM_X + TREE_OPTION_ITEM_W + MAIN_GUTTER_W)
#define MISSION_GROUP_Y									(ANCHOR_CORE_TOP_LEFT_Y + TREE_HEADER_H + TREE_OPTION_ITEM_Y)

#define MISSION_GROUP_W									(ANCHOR_CORE_BOTTOM_RIGHT_X - MISSION_GROUP_X)
#define MISSION_GROUP_H									(ANCHOR_CORE_BOTTOM_RIGHT_Y - MISSION_GROUP_Y - PROGRESS_H - MAIN_GUTTER_H)

// Core Mission Background
#define MISSION_BACKGROUND_X							(0)
#define MISSION_BACKGROUND_Y							(0)

#define MISSION_BACKGROUND_W							(MISSION_GROUP_W)
#define MISSION_BACKGROUND_H							(MISSION_GROUP_H)

// Core Mission Intel
#define MISSION_INTEL_X									(0)
#define MISSION_INTEL_Y									(0)
#define MISSION_INTEL_W									(MISSION_BACKGROUND_W)
#define MISSION_INTEL_H									(MISSION_INTEL_TEXT_Y + MISSION_INTEL_TEXT_H + MAIN_GUTTER_H)

// Core Mission Gutter
#define MISSION_INTEL_GUTTER_H							(MAIN_GUTTER_W)

// Core Mission Intel Background
#define MISSION_INTEL_BACKGROUND_X						(0)
#define MISSION_INTEL_BACKGROUND_Y						(0)
#define MISSION_INTEL_BACKGROUND_W						(MISSION_INTEL_W)
#define MISSION_INTEL_BACKGROUND_H						(MISSION_INTEL_H)

// Core Mission Title
#define MISSION_INTEL_TITLE_X							(0)
#define MISSION_INTEL_TITLE_Y							(0)
#define MISSION_INTEL_TITLE_W							(MISSION_INTEL_W)
#define MISSION_INTEL_TITLE_H							(xGUI_GRID_H * 2)

// Core Mission Text
#define MISSION_INTEL_TEXT_X							(0)
#define MISSION_INTEL_TEXT_Y							(MISSION_INTEL_TITLE_H)
#define MISSION_INTEL_TEXT_W							(MISSION_INTEL_W)
#define MISSION_INTEL_TEXT_H							(xGUI_GRID_H * 1.75)

// Core Mission Overview
#define MISSION_OVERLAY_X								(MISSION_BACKGROUND_X)
#define MISSION_OVERLAY_Y								(MISSION_BACKGROUND_Y)
#define MISSION_OVERLAY_W								(MISSION_BACKGROUND_W)
#define MISSION_OVERLAY_H								(MISSION_BACKGROUND_H)

// Core Mission Outlines
#define MISSION_OVERLAY_LINE01_X						(0)
#define MISSION_OVERLAY_LINE01_Y						(0)

#define MISSION_OVERLAY_LINE01_W						(MISSION_OVERLAY_W)
#define MISSION_OVERLAY_LINE01_H						(pixelH)

#define MISSION_OVERLAY_LINE02_Y						(MISSION_OVERLAY_H - MISSION_OVERLAY_LINE01_H)
#define MISSION_OVERLAY_LINE03_Y						(MISSION_OVERLAY_LINE01_H)

#define MISSION_OVERLAY_LINE03_W						(pixelW)

#define MISSION_OVERLAY_LINE03_H						(MISSION_OVERLAY_H - MISSION_OVERLAY_LINE01_H * 2)
#define MISSION_OVERLAY_LINE04_X						(MISSION_OVERLAY_W - MISSION_OVERLAY_LINE03_W)

#define MISSION_OVERLAY_COMPLETE_W						(xGUI_GRID_W * 6)
#define MISSION_OVERLAY_COMPLETE_H						(xGUI_GRID_H * 1)

// Core Players
#define MISSION_PLAYER_W								(MISSION_PLAYER_ITEM_W)
#define MISSION_PLAYER_H								(MISSION_GROUP_H)

#define MISSION_PLAYER_X								(0)
#define MISSION_PLAYER_Y								(0)

#define MISSION_PLAYER_SCALE							(1.5)
#define MISSION_PLAYER_ICON_SIZE						(MISSION_PLAYER_SCALE * 0.75)

#define MISSION_PLAYER_ITEM_W							(xGUI_GRID_W * 9)
#define MISSION_PLAYER_ITEM_H							(xGUI_GRID_H * MISSION_PLAYER_SCALE)

#define MISSION_PLAYER_ITEM_X							(0)
#define MISSION_PLAYER_ITEM_Y							(0)

#define MISSION_PLAYER_ITEM_GUTTER_H					(MISSION_PLAYER_ITEM_H + pixelH)

#define MISSION_PLAYER_ICON_GUTTER_W					(xGUI_GRID_W * 0.5)

#define MISSION_PLAYER_ITEM_STATUS_ICON_W				(xGUI_GRID_W * MISSION_PLAYER_ICON_SIZE)
#define MISSION_PLAYER_ITEM_STATUS_ICON_H				(xGUI_GRID_H * MISSION_PLAYER_ICON_SIZE)

#define MISSION_PLAYER_ITEM_STATUS_ICON_X				(MISSION_PLAYER_ITEM_W - MISSION_PLAYER_ITEM_STATUS_ICON_W - MISSION_PLAYER_ICON_GUTTER_W)
#define MISSION_PLAYER_ITEM_STATUS_ICON_Y				(MISSION_PLAYER_ITEM_H * 0.5 - MISSION_PLAYER_ITEM_STATUS_ICON_H * 0.5)

#define MISSION_PLAYER_ITEM_HOST_ICON_W					(xGUI_GRID_W * MISSION_PLAYER_ICON_SIZE)
#define MISSION_PLAYER_ITEM_HOST_ICON_H					(xGUI_GRID_H * MISSION_PLAYER_ICON_SIZE)

#define MISSION_PLAYER_ITEM_HOST_ICON_X					(MISSION_PLAYER_ITEM_W - MISSION_PLAYER_ITEM_STATUS_ICON_W - MISSION_PLAYER_ITEM_HOST_ICON_W - MISSION_PLAYER_ICON_GUTTER_W)
#define MISSION_PLAYER_ITEM_HOST_ICON_Y					(MISSION_PLAYER_ITEM_STATUS_ICON_Y)